### ISSUE TITLE
Missing a few languages from wikipedia. 

### ISSUE THREAD

**Issue by superlws1** [aymansalama/wikidownloader_java#13]
List of expected outputs is obtained from [here](https://meta.wikimedia.org/wiki/List_of_Wikipedias/sortable).

Correct: 280 / 302
No of incorrect: 2
Incorrect: {anp=Angika, be-x-old=Belarusian (Taraškievica)}

**Comment by amirulumar** [comment]
Developer for languages function here. Is this the same for the other Wikimedia projects (Wikinews, Wikibooks, Wikiversity, etc)?

**Comment by superlws1** [comment]
currently i've only tested on wikipedia, will let u know tomorrow about the others

**Comment by amirulumar** [comment]
I believe the problem is the fact I didn't use the list of languages that you linked in your first comment. I was instead using this site [here](https://meta.wikimedia.org/wiki/Table_of_Wikimedia_projects) for retrieving the list. My initial implementation did not take your list into consideration. I will redo my implementation in order to incorporate lists like this for each project.

**Comment by superlws1** [comment]
Honestly, i'm not sure which of the 2 website is actually correct. There might be some language that are quite obsolete which the [dump list](https://dumps.wikimedia.org/backup-index-bydb.html) here doesn't include those language (e.g. anp, but be-x-old exists)

**Comment by amirulumar** [comment]
Never mind, I'll redo the code and you can see.
